### ISSUE TITLE
Add support for structs

### ISSUE THREAD

**Issue by ash-nolan** [ash-nolan/sunder#31]
```
struct foo {
    var a: s32;
    var b: bool;
    var c: *foo;
    var d: []foo;
    # var e: foo; <-- self referential field should be an error
}

const bar: foo = (:foo){
    .a = 1s32,
    .b = true,
    .c = some_foo_ptr,
    .d = some_foo_slice,
};
```

## Notes
+ IIRC array element stride is calculated based on `sizeof` the element type. With the addition of non aligned fields the array stride should be calculated based on the `sizeof` the type rounded up to the nearest `alignof` the type.
+ ~~How should member functions be handled?~~ <-- leave for another issue.

## Tasks
+ [x] Add struct declarations to language grammar and compiler.
+ [x] Add struct literals to language grammar and compiler.
+ [x] Add struct member access operator to language grammar and compiler.

**Comment by ash-nolan** [comment]
Added with commits c4e5355e83f4f3a0eda9381bb7667455be24d4d2, 690b7fffccff08c2608114b4b807200531c6c65f, bbc5532def3c5e8e610af21a9c88d16100ac531a, and 225f8b5ea589bdfdc853a2dbf4140b71bb8e08b3.
